### ISSUE TITLE
problem in `Msgpck.String`?

### ISSUE THREAD

**Issue by c-cube** [vbmithr/ocaml-msgpck#11] opened 2020-01-08 19:59 UTC
using the following code, I get the following error (which doesn't happen with the commented code that uses Buffer instead of Bytes).
Might be related to #7.

```
$ dune exec ./msgpck_of_fs.exe .
write msgpck to 'foo.msgpck'
Fatal error: exception Invalid_argument("String.blit / Bytes.blit_string")
```

```ocaml
(* msgpck_of_fs.ml *)
module M = Msgpck

let rec fs_to_cbor ~path (f:string) : M.t =
  let file = Filename.concat path f in
  if not @@ Sys.file_exists file then M.String "<not found>"
  else if Sys.is_directory file then (
    try
      let dir = Sys.readdir file in
      M.Map [
        M.String f,
        M.List (Array.map (fs_to_cbor ~path:file) dir |> Array.to_list)
      ]
    with e ->
      M.String (Printf.sprintf "<exn for dir %S: %s>" f (Printexc.to_string e))
  ) else (
    let content =
      try
        let s = CCIO.with_in file CCIO.read_all in
        if CCUtf8_string.is_valid s then M.String s else M.Bytes s
      with _e ->
        M.String"<read error>"
      in
    M.Map [
      M.String f,
      M.List [content]
    ]
  )

let () =
  let out = ref "foo.msgpck" in
  let dirs = ref [] in
  Arg.parse (Arg.align [
      "-o", Arg.Set_string out, " output file";
    ]) (fun x -> dirs := x :: !dirs) "cbor_of_fs [-o <out>] <dir>+";
  if !out = "" then failwith "-o is required";
  if !dirs = [] then failwith "please provide at least one directory to pack";
  let cs = List.map (fs_to_cbor ~path:"") !dirs in
  let c = match cs with [x] -> x | _ -> M.List cs in
  Format.printf "write msgpck to %s@." (Filename.quote !out);
  CCIO.with_out !out
    (fun oc -> output_bytes oc @@ M.String.to_string c)
  (*
  let buf = Buffer.create 1024 in
  let n = M.StringBuf.write buf c in
  Format.printf "wrote %d bytes@." n;
  CCIO.with_out !out
    (fun oc -> Buffer.output_buffer oc buf)
     *)
```
```
; dune file
(executables
  (names msgpck_of_fs)
  (libraries containers msgpck))
```

**Comment by vbmithr** [comment] 2020-01-10 10:27
Whow, cannot reproduce!

**Comment by vbmithr** [comment] 2020-01-10 16:57
Fixed in master, drafting a new release now.

**Closed as completed by vbmithr** 2020-01-10 16:57 UTC
